# Generated by Django 5.0.4 on 2025-03-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itineraries',
            old_name='days',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='itineraries',
            old_name='end_date',
            new_name='return_date',
        ),
    ]
