# Generated by Django 5.0.4 on 2025-05-26 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_rename_days_itineraries_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('google_place_name', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Place Cards',
                'ordering': ['date', 'order', 'start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='itineraries',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Itineraries'},
        ),
        migrations.RemoveField(
            model_name='itineraries',
            name='duration',
        ),
        migrations.AddField(
            model_name='itineraries',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itineraries',
            name='destination_city',
            field=models.CharField(default='Bangkok', max_length=100),
        ),
        migrations.AddField(
            model_name='itineraries',
            name='destination_country',
            field=models.CharField(default='Thailand', max_length=100),
        ),
        migrations.AddField(
            model_name='itineraries',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itineraries',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itineraries',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='itineraries',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='itineraries',
            index=models.Index(fields=['user', '-start_date'], name='itinerary_i_user_id_19a987_idx'),
        ),
        migrations.AddField(
            model_name='placecards',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_cards', to='itinerary.itineraries'),
        ),
        migrations.AddIndex(
            model_name='placecards',
            index=models.Index(fields=['itinerary', 'date', 'order'], name='itinerary_p_itinera_1268a5_idx'),
        ),
        migrations.AddIndex(
            model_name='placecards',
            index=models.Index(fields=['google_place_id'], name='itinerary_p_google__346751_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='placecards',
            unique_together={('itinerary', 'date', 'order')},
        ),
    ]
